'use strict';
/**
 * core/builder-engine.js — AIOS Builder Engine v1.0.0
 *
 * Generates new modules, scripts, config files, and templates at runtime.
 * Allows the AIOS system to self-expand by building out new components on demand.
 *
 * Capabilities:
 *   - Scaffold a new core module (CommonJS factory, tests, registration stub)
 *   - Generate POSIX shell scripts with Termux-safe shebang and guards
 *   - Produce service config JSON files for /etc/aios/services/
 *   - List all generated artefacts (build registry)
 *   - Write artefacts to VFS and optionally to the host filesystem
 *
 * Terminal commands:
 *   build                     — show builder status + artefact count
 *   build status              — same
 *   build module <name>       — scaffold a new core module
 *   build script <name>       — generate a shell script template
 *   build config <name>       — generate a service config JSON
 *   build test <name>         — generate a Jest test stub
 *   build list                — list generated artefacts
 *   build help                — show help
 *
 * Integration (bootstrap.js):
 *   const { createBuilderEngine } = require('../core/builder-engine');
 *   const builder = createBuilderEngine(kernel, vfs, hostBridge);
 *   router.use('builder-engine', builder);
 *
 * Zero external npm dependencies.
 */

const nodefs   = require('fs');
const nodepath = require('path');
const os       = require('os');

const VERSION = '1.0.0';

// Base directory where artefacts are written to VFS
const VFS_BUILD_ROOT  = '/var/lib/aios/builder';
// Optional host FS output (relative to cwd when applicable)
const HOST_BUILD_ROOT = nodepath.join(os.homedir(), '.aios', 'builder');

// ── Module template ────────────────────────────────────────────────────────

function _moduleTemplate(name) {
  const safeName = _safeName(name);
  const factoryFn = `create${_pascalCase(safeName)}`;
  return `'use strict';
/**
 * core/${safeName}.js — AIOS ${_titleCase(safeName)} v1.0.0
 *
 * Auto-generated by AIOS Builder Engine v${VERSION}.
 * Expand this module with your implementation.
 *
 * Integration (bootstrap.js):
 *   const { ${factoryFn} } = require('../core/${safeName}');
 *   const ${safeName} = ${factoryFn}(kernel, router);
 *   router.use('${safeName}', ${safeName});
 *
 * Zero external npm dependencies.
 */

const VERSION = '1.0.0';

// ---------------------------------------------------------------------------
// ${factoryFn} — factory
// ---------------------------------------------------------------------------
function ${factoryFn}(kernel, router) {
  const _bus = (kernel && kernel.bus) ? kernel.bus : { emit: () => {} };

  // ── State ──────────────────────────────────────────────────────────────
  let _started = false;

  // ── Public API ─────────────────────────────────────────────────────────

  function start() {
    if (_started) return;
    _started = true;
    _bus.emit('${safeName}:started', { version: VERSION });
  }

  function stop() {
    if (!_started) return;
    _started = false;
    _bus.emit('${safeName}:stopped', {});
  }

  function status() {
    return { name: '${safeName}', version: VERSION, started: _started };
  }

  // ── Terminal commands ──────────────────────────────────────────────────

  const commands = {
    '${safeName}': (args) => {
      const sub = Array.isArray(args) ? args[0] : args;
      if (!sub || sub === 'status') {
        return { status: 'ok', result: \`${_titleCase(safeName)} v\${VERSION} — started: \${_started}\` };
      }
      if (sub === 'start') { start(); return { status: 'ok', result: 'Started.' }; }
      if (sub === 'stop')  { stop();  return { status: 'ok', result: 'Stopped.' }; }
      return { status: 'ok', result: 'Usage: ${safeName} [status|start|stop]' };
    },
  };

  return {
    name:    '${safeName}',
    version: VERSION,
    start,
    stop,
    status,
    commands,
  };
}

module.exports = { ${factoryFn}, VERSION };
`;
}

// ── Test template ──────────────────────────────────────────────────────────

function _testTemplate(name) {
  const safeName = _safeName(name);
  const factoryFn = `create${_pascalCase(safeName)}`;
  return `'use strict';
/**
 * tests/${safeName}.test.js — AIOS ${_titleCase(safeName)} tests
 *
 * Auto-generated by AIOS Builder Engine v${VERSION}.
 */

const { ${factoryFn} } = require('../core/${safeName}');

function makeKernel() {
  return {
    bus: { emit: jest.fn(), on: jest.fn() },
    modules: { load: jest.fn(), list: jest.fn(() => []) },
    uptime: jest.fn(() => 0),
  };
}

describe('${safeName}', () => {
  let kernel;

  beforeEach(() => { kernel = makeKernel(); });

  test('factory returns expected API', () => {
    const m = ${factoryFn}(kernel, null);
    expect(m.name).toBe('${safeName}');
    expect(typeof m.version).toBe('string');
    expect(typeof m.start).toBe('function');
    expect(typeof m.stop).toBe('function');
    expect(typeof m.status).toBe('function');
    expect(typeof m.commands).toBe('object');
  });

  test('works with null kernel', () => {
    expect(() => ${factoryFn}(null, null)).not.toThrow();
  });

  test('start / stop lifecycle', () => {
    const m = ${factoryFn}(kernel, null);
    m.start();
    expect(m.status().started).toBe(true);
    m.stop();
    expect(m.status().started).toBe(false);
  });

  test('start is idempotent', () => {
    const m = ${factoryFn}(kernel, null);
    m.start(); m.start();
    expect(m.status().started).toBe(true);
  });

  test('status command returns result string', () => {
    const m   = ${factoryFn}(kernel, null);
    const res = m.commands['${safeName}']([]);
    expect(res.status).toBe('ok');
    expect(typeof res.result).toBe('string');
  });
});
`;
}

// ── Shell script template ──────────────────────────────────────────────────

function _scriptTemplate(name) {
  const safeName = _safeName(name);
  return `#!/usr/bin/env sh
# ============================================================
# ${safeName}.sh — AIOS ${_titleCase(safeName)} Script v1.0.0
# Auto-generated by AIOS Builder Engine v${VERSION}.
#
# POSIX-compliant. Termux-safe (no root, no sudo).
# Compatible with: /data/data/com.termux/files/home/
# ============================================================
set -eu

SCRIPT_NAME="${safeName}"
AIOS_HOME="\${AIOS_HOME:-\${HOME}/aioscpu}"

# ── Colours (optional — disable if not a tty) ──────────────────────────────
if [ -t 1 ]; then
  R='\\033[0;31m'; G='\\033[0;32m'; Y='\\033[0;33m'; C='\\033[0;36m'; W='\\033[0m'
else
  R=''; G=''; Y=''; C=''; W=''
fi

info()  { printf "%b[INFO]%b  %s\\n" "\${C}" "\${W}" "\$*"; }
ok()    { printf "%b[ OK ]%b  %s\\n" "\${G}" "\${W}" "\$*"; }
warn()  { printf "%b[WARN]%b  %s\\n" "\${Y}" "\${W}" "\$*"; }
fail()  { printf "%b[FAIL]%b  %s\\n" "\${R}" "\${W}" "\$*"; exit 1; }

# ── Entry point ────────────────────────────────────────────────────────────

main() {
  info "Running \${SCRIPT_NAME} from \${AIOS_HOME}"

  # ── Verify AIOS home ──────────────────────────────────────────────────
  if [ ! -d "\${AIOS_HOME}" ]; then
    fail "AIOS home not found: \${AIOS_HOME}. Run the installer first."
  fi

  # ── TODO: add your logic here ─────────────────────────────────────────

  ok "\${SCRIPT_NAME} complete."
}

main "\$@"
`;
}

// ── Service config template ────────────────────────────────────────────────

function _serviceConfigTemplate(name) {
  const safeName = _safeName(name);
  return JSON.stringify({
    name:        safeName,
    description: `${_titleCase(safeName)} service — auto-generated by AIOS Builder Engine v${VERSION}`,
    command:     `node /etc/aios/services/${safeName}.js`,
    autostart:   false,
    restartOnFail: false,
    interval:    30000,
    _generated:  new Date().toISOString(),
  }, null, 2) + '\n';
}

// ── Name helpers ───────────────────────────────────────────────────────────

function _safeName(s) {
  return String(s || 'unnamed')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 64);
}

function _pascalCase(s) {
  return s.split('-').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function _titleCase(s) {
  return s.split('-').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');
}

// ── Build registry ─────────────────────────────────────────────────────────
// Tracks every artefact generated this session.

// ---------------------------------------------------------------------------
// createBuilderEngine — factory
// ---------------------------------------------------------------------------
function createBuilderEngine(kernel, vfs, hostBridge) {
  const _bus = (kernel && kernel.bus) ? kernel.bus : { emit: () => {} };

  // Registry: name → { type, vfsPath, hostPath?, ts, size }
  const _registry = new Map();

  // ── Write helpers ────────────────────────────────────────────────────────

  function _writeToVFS(vfsPath, content) {
    if (!vfs) return { ok: false, error: 'No VFS available' };
    try {
      // Ensure parent dirs exist
      const parts = vfsPath.split('/').filter(Boolean);
      parts.pop(); // remove filename
      let dir = '';
      for (const p of parts) {
        dir += '/' + p;
        try { vfs.mkdir(dir); } catch (_) {}
      }
      return vfs.write(vfsPath, content);
    } catch (e) {
      return { ok: false, error: e.message };
    }
  }

  function _writeToHost(hostPath, content) {
    try {
      nodefs.mkdirSync(nodepath.dirname(hostPath), { recursive: true });
      nodefs.writeFileSync(hostPath, content, 'utf8');
      return { ok: true };
    } catch (e) {
      return { ok: false, error: e.message };
    }
  }

  function _register(name, type, vfsPath, hostPath, size) {
    _registry.set(`${type}:${name}`, {
      name, type, vfsPath, hostPath: hostPath || null,
      ts: new Date().toISOString(), size: size || 0,
    });
    _bus.emit('builder:artefact', { name, type, vfsPath });
  }

  // ── Build operations ─────────────────────────────────────────────────────

  function buildModule(name) {
    const safe     = _safeName(name);
    const content  = _moduleTemplate(safe);
    const vfsPath  = `${VFS_BUILD_ROOT}/modules/${safe}.js`;
    const hostPath = nodepath.join(HOST_BUILD_ROOT, 'modules', `${safe}.js`);

    const vfsResult  = _writeToVFS(vfsPath, content);
    const hostResult = _writeToHost(hostPath, content);

    _register(safe, 'module', vfsPath, hostResult.ok ? hostPath : null, content.length);

    return {
      ok: true,
      name:     safe,
      type:     'module',
      vfsPath,
      hostPath: hostResult.ok ? hostPath : null,
      content,
      vfsResult,
    };
  }

  function buildTest(name) {
    const safe     = _safeName(name);
    const content  = _testTemplate(safe);
    const vfsPath  = `${VFS_BUILD_ROOT}/tests/${safe}.test.js`;
    const hostPath = nodepath.join(HOST_BUILD_ROOT, 'tests', `${safe}.test.js`);

    const vfsResult  = _writeToVFS(vfsPath, content);
    const hostResult = _writeToHost(hostPath, content);

    _register(safe, 'test', vfsPath, hostResult.ok ? hostPath : null, content.length);

    return {
      ok: true,
      name:     safe,
      type:     'test',
      vfsPath,
      hostPath: hostResult.ok ? hostPath : null,
      content,
      vfsResult,
    };
  }

  function buildScript(name) {
    const safe     = _safeName(name);
    const content  = _scriptTemplate(safe);
    const vfsPath  = `${VFS_BUILD_ROOT}/scripts/${safe}.sh`;
    const hostPath = nodepath.join(HOST_BUILD_ROOT, 'scripts', `${safe}.sh`);

    const vfsResult  = _writeToVFS(vfsPath, content);
    const hostResult = _writeToHost(hostPath, content);
    if (hostResult.ok) {
      try { nodefs.chmodSync(hostPath, 0o755); } catch (_) {}
    }

    _register(safe, 'script', vfsPath, hostResult.ok ? hostPath : null, content.length);

    return {
      ok: true,
      name:     safe,
      type:     'script',
      vfsPath,
      hostPath: hostResult.ok ? hostPath : null,
      content,
      vfsResult,
    };
  }

  function buildConfig(name) {
    const safe     = _safeName(name);
    const content  = _serviceConfigTemplate(safe);
    const vfsPath  = `${VFS_BUILD_ROOT}/configs/${safe}.json`;
    const hostPath = nodepath.join(HOST_BUILD_ROOT, 'configs', `${safe}.json`);

    const vfsResult  = _writeToVFS(vfsPath, content);
    const hostResult = _writeToHost(hostPath, content);

    _register(safe, 'config', vfsPath, hostResult.ok ? hostPath : null, content.length);

    return {
      ok: true,
      name:     safe,
      type:     'config',
      vfsPath,
      hostPath: hostResult.ok ? hostPath : null,
      content,
      vfsResult,
    };
  }

  // ── List / status ─────────────────────────────────────────────────────────

  function listArtefacts() {
    return [..._registry.values()];
  }

  function status() {
    const counts = { module: 0, test: 0, script: 0, config: 0 };
    for (const a of _registry.values()) {
      if (counts[a.type] !== undefined) counts[a.type]++;
    }
    return {
      name:       'builder-engine',
      version:    VERSION,
      artefacts:  _registry.size,
      byType:     counts,
      hostRoot:   HOST_BUILD_ROOT,
      vfsRoot:    VFS_BUILD_ROOT,
    };
  }

  // ── Template getters (for testing / inspection) ───────────────────────────

  function getModuleTemplate(name) { return _moduleTemplate(_safeName(name)); }
  function getTestTemplate(name)   { return _testTemplate(_safeName(name));   }
  function getScriptTemplate(name) { return _scriptTemplate(_safeName(name)); }
  function getConfigTemplate(name) { return _serviceConfigTemplate(_safeName(name)); }

  // ── Terminal commands ─────────────────────────────────────────────────────

  function _statusTable() {
    const s = status();
    const lines = [
      '╔══════════════════════════════════════════════════════╗',
      '║          AIOS Builder Engine  v' + VERSION.padEnd(22) + '║',
      '╠══════════════════════════════════════════════════════╣',
      `║  Artefacts built : ${String(s.artefacts).padEnd(34)} ║`,
      `║  Modules         : ${String(s.byType.module).padEnd(34)} ║`,
      `║  Tests           : ${String(s.byType.test).padEnd(34)} ║`,
      `║  Scripts         : ${String(s.byType.script).padEnd(34)} ║`,
      `║  Configs         : ${String(s.byType.config).padEnd(34)} ║`,
      `║  Host root       : ${String(s.hostRoot).slice(0, 34).padEnd(34)} ║`,
      '╚══════════════════════════════════════════════════════╝',
    ];
    return { status: 'ok', result: lines.join('\n') };
  }

  const commands = {
    build: (args) => {
      const parts = Array.isArray(args) ? args : String(args || '').split(' ').filter(Boolean);
      const sub   = parts[0];
      const nameArg = parts[1];

      if (!sub || sub === 'status') return _statusTable();

      if (sub === 'help') {
        return {
          status: 'ok',
          result: [
            'Usage: build <sub-command> [name]',
            '  build status          — show builder status',
            '  build module <name>   — scaffold a new core module',
            '  build test <name>     — generate a Jest test stub',
            '  build script <name>   — generate a shell script',
            '  build config <name>   — generate a service config',
            '  build list            — list generated artefacts',
            '  build help            — show this help',
          ].join('\n'),
        };
      }

      if (sub === 'list') {
        const list = listArtefacts();
        if (!list.length) return { status: 'ok', result: 'No artefacts generated yet.' };
        const lines = ['Generated artefacts:', ''];
        for (const a of list) {
          lines.push(`  [${a.type.padEnd(6)}] ${a.name}  →  ${a.vfsPath}`);
        }
        return { status: 'ok', result: lines.join('\n') };
      }

      if (!nameArg) {
        return { status: 'error', result: `Usage: build ${sub} <name>` };
      }

      let r;
      if (sub === 'module') r = buildModule(nameArg);
      else if (sub === 'test')   r = buildTest(nameArg);
      else if (sub === 'script') r = buildScript(nameArg);
      else if (sub === 'config') r = buildConfig(nameArg);
      else return { status: 'error', result: `Unknown sub-command: ${sub}. Run 'build help'.` };

      const lines = [
        `Built ${r.type}: ${r.name}`,
        `  VFS  : ${r.vfsPath}`,
      ];
      if (r.hostPath) lines.push(`  Host : ${r.hostPath}`);
      return { status: 'ok', result: lines.join('\n') };
    },
  };

  // ── Public API ────────────────────────────────────────────────────────────

  return {
    name:    'builder-engine',
    version: VERSION,

    buildModule,
    buildTest,
    buildScript,
    buildConfig,
    listArtefacts,
    status,

    // Template accessors
    getModuleTemplate,
    getTestTemplate,
    getScriptTemplate,
    getConfigTemplate,

    // Terminal
    commands,
  };
}

module.exports = { createBuilderEngine, VERSION };
